version: "3.8"
services:
  web:
    restart: always
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/code
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - "5434:5434"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pg_data:
    driver: local