# Generated by Django 5.0.6 on 2024-06-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, help_text='Фото сотрудника', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
